procs:
  SMS-TStauStau_MStau-90_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-90_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-90_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-90_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-90_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-90_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-90_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-90_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-90_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-90_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-90_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-90_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-100_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-100_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-100_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-100_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-100_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-100_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-100_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-100_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-100_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-100_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-100_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-100_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-125_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-125_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-125_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-125_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-125_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-125_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-125_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-125_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-125_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-125_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-125_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-125_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-150_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-150_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-150_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-150_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-150_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-150_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-150_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-150_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-150_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-150_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-150_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-150_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-175_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-175_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-175_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-175_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-175_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-175_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-175_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-175_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-175_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-175_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-175_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-175_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-200_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-200_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-200_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-200_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-200_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-200_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-200_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-200_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-200_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-200_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-200_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-200_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-225_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-225_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-225_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-225_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-225_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-225_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-225_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-225_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-225_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-225_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-225_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-225_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-250_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-250_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-250_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-250_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-250_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-250_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-250_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-250_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-250_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-250_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-250_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-250_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-275_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-275_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-275_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-275_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-275_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-275_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-275_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-275_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-275_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-275_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-275_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-275_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-300_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-300_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-300_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-300_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-300_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-300_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-300_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-300_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-300_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-300_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-300_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-300_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-350_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-350_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-350_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-350_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-350_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-350_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-350_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-350_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-350_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-350_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-350_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-350_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-400_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-400_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-400_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-400_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-400_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-400_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-400_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-400_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-400_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-400_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-400_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-400_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-450_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-450_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-450_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-450_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-450_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-450_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-450_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-450_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-450_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-450_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-450_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-450_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-500_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-500_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-500_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-500_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-500_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-500_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-500_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-500_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-500_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-500_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-500_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-500_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-550_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-550_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-550_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-550_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-550_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-550_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-550_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-550_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-550_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-550_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-550_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-550_ctau-1000mm_mLSP-1
  SMS-TStauStau_MStau-600_ctau-1mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-600_ctau-1mm_mLSP-1
  SMS-TStauStau_MStau-600_ctau-5mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-600_ctau-5mm_mLSP-1
  SMS-TStauStau_MStau-600_ctau-10mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-600_ctau-10mm_mLSP-1
  SMS-TStauStau_MStau-600_ctau-50mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-600_ctau-50mm_mLSP-1
  SMS-TStauStau_MStau-600_ctau-100mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-600_ctau-100mm_mLSP-1
  SMS-TStauStau_MStau-600_ctau-1000mm_mLSP-1:
    ismc: true
    issusy: true
    xsnorm: true
    scaleby: '0.64'
    samples:
    - SMS-TStauStau_MStau-600_ctau-1000mm_mLSP-1
