#procs:
#  
#  obs:
#    label: "Data"
#  
#  misid:
#    label: "Misid. jets"
#  
#  SMS-TStauStau_MStau-100_ctau-50mm_mLSP-1:
#      label: "${[m_{\PSGt}(100),\ c\tau_{0}(50)]}$"
#  SMS-TStauStau_MStau-100_ctau-100mm_mLSP-1:
#    label: "${[m_{\PSGt}(100),\ c\tau_{0}(100)]}$"
#  SMS-TStauStau_MStau-200_ctau-50mm_mLSP-1:
#    label: "${[m_{\PSGt}(200),\ c\tau_{0}(50)]}$"
#  SMS-TStauStau_MStau-200_ctau-100mm_mLSP-1:
#    label: "${[m_{\PSGt}(200), c\tau_{0}(100)]}$"

obs: # This key is the type of process. Must be one of [obs, bkg, sig]
  obs: # This key needs to be there in the input yaml
    label: "Data"

bkg:
  misid:
    label: "Misid. jets"
    color: "#92dadd"

sig:
  SMS-TStauStau_MStau-100_ctau-50mm_mLSP-1:
      label: "${[m_{\\PSGt}(100),\\ c\\tau_{0}(50)]}$"
      color: "#bd1f01"
      linestyle: 7
  
  SMS-TStauStau_MStau-100_ctau-100mm_mLSP-1:
    label: "${[m_{\\PSGt}(100),\\ c\\tau_{0}(100)]}$"
    color: "#bd1f01"
    linestyle: 10
  
  SMS-TStauStau_MStau-200_ctau-50mm_mLSP-1:
    label: "${[m_{\\PSGt}(200),\\ c\\tau_{0}(50)]}$"
    color: "#832db6"
    linestyle: 7
  
  SMS-TStauStau_MStau-200_ctau-100mm_mLSP-1:
    label: "${[m_{\\PSGt}(200), c\\tau_{0}(100)]}$"
    color: "#832db6"
    linestyle: 10

bin_header: "SR bins"

plot_bins: [3, 4, 5, 6, 7, 8, 9, 10]

bins:
  3:
    label: 1
  4:
    label: 2
  5:
    label: 3
  6:
    label: 4
  7:
    label: 5
  8:
    label: 6
  9:
    label: 7
  10:
    label: 8
  total:
    label: "Total"
